version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: ts_build
    ports:
      - 5000:5000
      - 9229:9229
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules/
    command: >
      sh -c "yarn run build && yarn run start --inspect=0.0.0.0"
    environment:
      PORT: 5000
